#!/usr/bin/env python3

# %%
import re
import requests
from bs4 import BeautifulSoup

user_input = input("Enter the tracking ID : ")
user_input = user_input.upper()

# %%
baseurl = "https://ekartlogistics.com/shipmenttrack/"
URL = baseurl + user_input

# %%

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36 QIHU 360SE'
}
f = requests.get(URL, headers=headers)
if not f.ok:
    raise Exception("GET failed with status code {}".format(f.status_code))

soup = BeautifulSoup(f.content, 'html.parser')

# %%

# Run into a problem since the data i require is NOT in the HTML
# file being received by enterong URL. Its being generated by js
# have to study up more about web then maybe finish this
